name: 'slab github integration'
description: 'Acces methods to create and update posts on slab'
inputs: 
  repo_name:
    description: 'repository name'
    required: true
  repo_owner:
    description: 'repository owner'
    required: true
  accessToken_slab:
      description: 'valid slab api token'
      required: true
  accessToken_github:
    description: 'valid github api token'
    required: true
outputs:
  name:
    description: 'just a test for now'

runs:
  using: 'composite'
  steps:
    - run: |
        ruby scripts/main.rb ${{ inputs.repo_name }} ${{ inputs.repo_owner }} ${{ inputs.accessToken_slab }} ${{ inputs.accessToken_github }}
      shell: bash
